django101/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

urlpatterns = [
	path('project/', include('project.urls')),
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('project.urls')),
]

project/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('project/add/', views.addProject, name='addProject'),
    path('project/edit/<int:project_id>', views.addProject, name='addProject'),
    path('project/delete/<int:project_id>', views.deleteProject, name='deleteProject'),
    path('project/pdf/<int:project_id>', views.downloadProject, name='downloadProject'),
    path('<int:project_id>/', views.detail, name='detail'),
]

project/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=200)
    phrase = models.CharField(max_length=200)
    status = models.BooleanField(default = 0)

    def save(self, *args, **kwargs):
        super(Project, self).save(*args, **kwargs)
        
        from project.tasks import save_details

        save_details.delay(self.pk, self.phrase)

    def __str__(self):
        return self.name

class Detail(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    title = models.CharField(max_length=254)
    link = models.CharField(max_length=254)
    numviews = models.CharField(max_length=200)
    numfollowers = models.CharField(max_length=200)
    numanswers = models.CharField(max_length=200)
    questiondate = models.DateField(auto_now=False, auto_now_add=False)

    def __str__(self):
        return self.link

project/forms.py
from django import forms
from .models import Project, Detail

class ProjectForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = ('name', 'phrase')

project/views.py
from django.http import HttpResponse
from django.shortcuts import redirect
from django.template import loader

from .models import Project, Detail
from .forms import ProjectForm

def index(request):
    if request.user.is_authenticated:
        projects = Project.objects.all();
        template = loader.get_template('project/projects.html')
        context = {
            'projects': projects,
            'id' : 'projects',
        }
        return HttpResponse(template.render(context, request))
    else:
        return redirect('/login')

def detail(request, project_id):
    if request.user.is_authenticated:
        details = Detail.objects.filter(project_id=project_id);
        template = loader.get_template('project/details.html')
        context = {
            'details': details,
            'id' : 'projects',
        }
        return HttpResponse(template.render(context, request))
    else:
        return redirect('/login')

def deleteProject(request, project_id):
    Detail.objects.filter(project_id=project_id).delete();
    Project.objects.filter(id=project_id).delete();

    projects = Project.objects.all();
    template = loader.get_template('project/projects.html')
    context = {
        'projects': projects,
        'id' : 'projects',
    }
    return HttpResponse(template.render(context, request))

def downloadProject(request, project_id):
    Detail.objects.filter(project_id=project_id).delete();
    Project.objects.filter(id=project_id).delete();

    # projects = Project.objects.all();
    # template = loader.get_template('project/projects.html')
    # context = {
    #     'projects': projects,
    #     'id' : 'projects',
    # }
    # return HttpResponse(template.render(context, request))

    import io
    from django.http import FileResponse
    from reportlab.pdfgen import canvas

    def some_view(request):
        # Create a file-like buffer to receive PDF data.
        buffer = io.BytesIO()

        # Create the PDF object, using the buffer as its "file."
        p = canvas.Canvas(buffer)

        # Draw things on the PDF. Here's where the PDF generation happens.
        # See the ReportLab documentation for the full list of functionality.
        p.drawString(100, 100, "Hello world.")

        # Close the PDF object cleanly, and we're done.
        p.showPage()
        p.save()

        # FileResponse sets the Content-Disposition header so that browsers
        # present the option to save the file.
        return FileResponse(buffer, as_attachment=True, filename='hello.pdf')

def addProject(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            form = ProjectForm(request.POST)

            if form.is_valid():
                post = form.save(commit=False)
                post.save()


            projects = Project.objects.all();

            context = {
                'id' : 'projects',
                'projects': projects,
            }

            template = loader.get_template('project/projects.html')
            return HttpResponse(template.render(context, request))

        else:
            form = ProjectForm()

            project = [];
            template = loader.get_template('project/addProject.html')
            context = {
                'projects': project,
                'form': form,
                'id' : 'createproject',
            }
            return HttpResponse(template.render(context, request))
    else:
        return redirect('/login')

project/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  	<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
	<!-- <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script> -->
	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<link rel="stylesheet" href="{% static 'project/css/style.css' %}">
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

project/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
{% endif %}
{% endblock %}

project/templates/project/addProject.html
{% extends 'project/base.html' %}

{% block content %}
    <div class="container">
		<h1 class="form-heading">Create Project</h1>
		<div class="login-form">
			<div class="main-div">
				<div class="panel">
			   		<h2>Create Project</h2>
			   	</div>
			    <form id="Login" method="POST">
			    	{% csrf_token %}
			        <div class="form-group">
			            <input type="text" class="form-control" placeholder="Project Name" name="name" id="id_name" maxlength="200" required>
			        </div>
			        <div class="form-group">
			            <input type="text" class="form-control" name="phrase" id="id_phrase" maxlength="200" placeholder="Project Phrase" required>
			        </div>
			        <button type="submit" class="btn btn-primary">Create</button>
			    </form>
			</div>
		</div>
	</div>
{% endblock %}

project/templates/project/base.html
{% load static %}
<html>
    <head>
        <title>Quora Finder</title>
        <!-- <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />
        <link href="http://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css">
        <link href="{% static 'project/css/bootstrap-datetimepicker.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'project/css/jquery.datatables.yadcf.css' %}" rel="stylesheet" type="text/css" />

        <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'project/js/moment.js' %}"></script>
        <script src="{% static 'project/js/bootstrap-datetimepicker.js' %}"></script>
        <script src="{% static 'project/js/jquery.dataTables.yadcf.js' %}"></script>
        <link rel="stylesheet" href="{% static 'project/css/style.css' %}"> -->

        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
        <link href="http://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{% static 'project/css/jquery.dataTables_themeroller.css' %}">
        <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />
        <link href="{% static 'project/css/jquery.datatables.yadcf.css' %}" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" href="{% static 'project/css/style.css' %}">

        <script src="{% static 'project/js/jquery-1.8.2.min.js' %}"></script>
        <script src="{% static 'project/js/jquery-ui.1.9.0.js' %}"></script>
        <script type="text/javascript" src="http://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
        <script src="{% static 'project/js/jquery.dataTables.yadcf.js' %}"></script>
        <script src="{% static 'project/js/app.js' %}"></script>
    </head>
    <body>
        <div class="page-header" style="margin-bottom: 2%;">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark w-100">
                <a class="navbar-brand" href="#">Quora Finder</a>
                <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item" id="createproject">
                            <a class="nav-link" href="http://{{ request.get_host }}/project/add">Create Project</a>
                        </li>
                        <li class="nav-item" id="projects">
                            <a class="nav-link" href="/">Projects</a>
                        </li>
                        <li class="nav-item" id="logout">
                            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                        </li>
                    </ul>
                </div>
            </nav>
            <!-- <a href="{% url 'addProject' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a> -->
        </div>
        <div class="content container" style="margin-bottom: 2%;>
            <div class="row">
                <div class="col-md-12">
                    {% block content %}
                        
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>

    <script type="text/javascript">
        $('#' + '{{ id }}').addClass('active');
    </script>

</html>

project/templates/project/details.html
{% extends 'project/base.html' %}

{% block content %}
	<style type="text/css">
		#datatable {width: 100%;}
	</style>

	<div>
    	<span>Date:</span>
    	<span id="external_filter_container_2"></span>
    </div>

    <div style="margin-bottom: 2%">
		<input type="button" onclick="yadcf.exFilterExternallyTriggered(oTable);" value="Filter" class="some_btn general_btn">
 		<input type="button" onclick="yadcf.exResetAllFilters(oTable);" value="Reset" class="some_btn general_btn">
  	</div>

	<table id="datatable2" class="tg">
	  <thead>
	  	<tr>
		    <th>Question</th>
		    <th>Views</th>
		    <th>Followers</th>
		    <th>Answers</th>
		    <th>Date</th>
		</tr>
	  </thead>
	  <tbody>
	  {% for detail in details %}
		  <tr>
		    <td><a href="{{ detail.link }}" target="_blank">{{ detail.title }}</a></li></td>
		    <td style="width: 10%;">{{ detail.numviews }}</td>
		    <td>{{ detail.numfollowers }}</td>
		    <td>{{ detail.numanswers }}</td>
		    <td style="width: 12%;">{{ detail.questiondate|date:"m/d/Y" }}</td>
		  </tr>
	  {% endfor %}
	  </tbody>
	</table>
{% endblock %}

project/templates/project/index.html
{% if projects %}
    <ul>
    {% for project in projects %}
        <li><a href="/project/{{ project.id }}/">{{ project.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

project/templates/project/projects.html
{% extends 'project/base.html' %}

{% block content %}
	{% if projects %}
		<style type="text/css">
			#datatable {width: 100%;}
		</style>
		<table id="datatable" class="display">
			<thead>
				<tr>
				    <th>#</th>
				    <th>Project Name</th>
				    <th>Keywords</th>
				    <th>Progress</th>
				    <th>Status</th>
				    <th>Download</th>
				    <th>Actions</th>
				  </tr>
			</thead>
		  	<tbody>
			  {% for project in projects %}
				  <tr>
				    <td class="tg-us36">{{ forloop.counter }}</td>
				    <td class="tg-us36"><a href="/project/{{ project.id }}/">{{ project.name }}</a></li></td>
				    <td class="tg-us36">{{ project.phrase }}</td>
				    <td class="tg-us36"></td>
				    {% if project.status %}
				    	<td class="tg-us36" style="background-color: green">Done</td>
				    	<td class="tg-us36">
				    		<button type="button" class="btn btn-default btn-sm">
					          <a href="/project/pdf/{{ project.id }}"><i class="fas fa-file-pdf" style="color: red;" data-toggle="tooltip" data-placement="top" title="Download"></i></a>
					        </button>
				    	</td>
				    {% else %}
				    	<td class="tg-us36" style="background-color: orange">In-progress</td>
				    	<td class="tg-us36"></td>
				    {% endif %}
				    <td class="tg-us36">
				    	<button type="button" class="btn btn-default btn-sm">
				          <a href="/project/delete/{{ project.id }}"><i class="fas fa-trash-alt" style="color: red;" data-toggle="tooltip" data-placement="top" title="Delete"></i></a>
				        </button>
				    </td>
				  </tr>
			  {% endfor %}
			  </tbody>
		</table>
	{% else %}
	    <p>No projects are available.</p>
	{% endif %}
{% endblock %}